### PR TITLE
Provide semigroup and monoid instances that build under 8.4.x and 8.2.x and 8.0.x

### PR DESCRIPTION
**Pull request by ixmatus**
To accommodate the new superclass constraints.

### CODE REVIEW

**Comment by nh2** [comment]
Thanks, I've cherry-picked it in commit eec2d657f316937fdbbf636365abda3a7ff60528 and made release https://hackage.haskell.org/package/shared-memory-0.2.0.0 on Hackage.

Do you care about adding the nix tooling as well?

So far my preference has been to have the `cabal2nix` stuff be generated as part of nixpkgs instead of being in the repo so I don't have to update it.

**Comment by nh2** [comment]
I also PRd it to stackage, so it will be in nixpkgs soon: https://github.com/commercialhaskell/stackage/pull/4112

**Comment by ixmatus** [comment]
@nh2 I like to include the rudiments of the nix tooling so that I can easily `nix-shell` with all of the project's dependencies and develop incrementally. For packages that support multiple versions of GHC it's also really nice because the way I wrote the `release.nix` you can specify a different GHC version and build against that, which is convenient too.

No biggie if you don't want to include it though.

**Comment by ixmatus** [comment]
Oops, upon inspection I forgot to commit the change to the Nix tooling that makes changing the compiler version easy. My bad. If you want it, I can push it to my branch. Let me know.

**Comment by nh2** [comment]
@ixmatus I can put it in if it's very useful for you, but I have a couple questions and requests to ease maintainability:

* Why is something ultra-generic and common like `fetchNixpkgs.nix` to be checked into each packages repo -- wouldn't it make sense to have that in nixpkgs instead?
* Also, wouldn't a much simpler approach be `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/a8ff26166.tar.gz nix-build/nix-shell ...`? That's how I do it in [static-haskell-nix](https://github.com/nh2/static-haskell-nix/). Does that approach have some drawbacks or inconveniences?
* I'm not super eager to have (and likely forget) to update `default.nix` on every release or addition of a dependency in the cabal file. It's essentially checking in a generated file (in this case, the output of `cabal2nix` ran agains the cabal file), which I'd like to avoid. Could this be solved with `callCabal2nix` instead, to avoid the checked-in generated file?

Thanks!

**Comment by ixmatus** [comment]
We never added it to `nixpkgs` because for Nix >= 1.12 you can just use `builtins.fetchTarball` but that doesn't work for pre-1.12 versions and we haven't upgraded to Nix 2.0 at work yet so we use a pinned nixpkgs bootstrapping function that works for pre and post 1.12 Nix.

Mutating the `NIX_PATH` to provide a pinned nixpkgs requires mutating the user's environment which I try to avoid at all costs. Additionally, pinning nixpkgs with a Nix expression makes it easier for a user to simply invoke `nix-shell` or `nix-build`.

I think `callCabal2nix` could work, I just haven't played with it. Let me see about using it.

**Comment by ixmatus** [comment]
Okay, I pushed a commit to my branch to parameterize the GHC compiler and use `callCabal2nix`.

**Pull request closed without merging**
